apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greyhat-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - www.greyh.at
    - greyh.at
    secretName: greyhat-tls
  defaultBackend:
    service:
      name: greyhat
      port:
        number: 201
  rules:
  - host: greyh.at
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: greyhat
            port:
              number: 201
  - host: www.greyh.at
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: greyhat
            port:
              number: 201
